export const dummyProducts = [
  {
    id: 1,
    name: "test",
    description: "2XL",
    price: 39.11,
    photo: "https://awgikyrvip.cloudimg.io/v7/_media_/media/image/ed/e5/50/1141-FrontImage-white.png",
  },
  {
    id: 2,
    name: "test",
    description: "2XL",
    price: 39.11,
    photo: "https://awgikyrvip.cloudimg.io/v7/_media_/media/image/ed/e5/50/1141-FrontImage-white.png",
  },
  {
    id: 3,
    name: "test",
    description: "2XL",
    price: 39.11,
    photo: "https://awgikyrvip.cloudimg.io/v7/_media_/media/image/ed/e5/50/1141-FrontImage-white.png",
  },
  {
    id: 4,
    name: "test",
    description: "2XL",
    price: 39.11,
    photo: "https://awgikyrvip.cloudimg.io/v7/_media_/media/image/ed/e5/50/1141-FrontImage-white.png",
  },
  {
    id: 5,
    name: "test",
    description: "2XL",
    price: 39.11,
    photo: "https://awgikyrvip.cloudimg.io/v7/_media_/media/image/ed/e5/50/1141-FrontImage-white.png",
  },
  {
    id: 6,
    name: "test",
    description: "2XL",
    price: 39.11,
    photo: "https://awgikyrvip.cloudimg.io/v7/_media_/media/image/ed/e5/50/1141-FrontImage-white.png",
  },
  {
    id: 7,
    name: "test",
    description: "2XL",
    price: 39.11,
    photo: "https://awgikyrvip.cloudimg.io/v7/_media_/media/image/ed/e5/50/1141-FrontImage-white.png",
  },
  {
    id: 8,
    name: "test",
    description: "2XL",
    price: 39.11,
    photo: "https://awgikyrvip.cloudimg.io/v7/_media_/media/image/ed/e5/50/1141-FrontImage-white.png",
  },
  {
    id: 9,
    name: "test",
    description: "2XL",
    price: 39.11,
    photo: "https://awgikyrvip.cloudimg.io/v7/_media_/media/image/ed/e5/50/1141-FrontImage-white.png",
  },
  {
    id: 10,
    name: "test",
    description: "2XL",
    price: 39.11,
    photo: "https://awgikyrvip.cloudimg.io/v7/_media_/media/image/ed/e5/50/1141-FrontImage-white.png",
  },
];
